services:
  - type: web
    name: rail-express-platform
    runtime: python
    buildCommand: pip install -r requirements.txt && python seed_db.py
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
